INSERT INTO ciudad_dep 
VALUES('BE','BENI',306,'TRINIDAD','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',307,'SAN JAVIER','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',308,'RIBERALTA','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',309,'GUAYARAMERIN','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',310,'REYES','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',311,'SAN BORJA','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',312,'SANTA ROSA','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',313,'RURRENABAQUE','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',314,'SANTA ANA','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',315,'EXALTACION','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',316,'SAN IGNACIO','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',317,'LORETO','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',318,'SAN ANDRES','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',319,'SAN JOAQUIN','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',320,'SAN RAMON','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',321,'PUERTO SILES','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',322,'MAGDALENA','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',323,'BAURES','U');
INSERT INTO ciudad_dep 
VALUES('BE','BENI',324,'HUACARAJE','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',117,'AIQUILE','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',118,'ALALAY','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',119,'ANZALDO','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',120,'ARANI','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',121,'ARBIETO','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',122,'ARQUE','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',123,'BOLIVAR','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',124,'CAPINOTA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',125,'CHIMORE','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',126,'CLIZA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',127,'COCAPATA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',128,'COCHABAMBA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',129,'COLCAPIRHUA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',130,'COLOMI','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',131,'CUCHUMUELA (VILLA GUALBERTO VILLARROEL)','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',132,'ENTRE RIOS (BULO BULO)','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',133,'INDEPENDENCIA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',134,'MIZQUE','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',135,'MOROCHATA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',136,'OMEREQUE','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',137,'PASORAPA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',138,'POCONA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',139,'POJO','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',140,'PUERTO VILLARROEL','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',141,'PUNATA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',142,'QUILLACOLLO','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',143,'SACABA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',144,'SACABAMBA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',145,'SAN BENITO','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',146,'SANTIVA?EZ','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',147,'SHINAHOTA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',148,'SICAYA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',149,'SIPE SIPE','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',150,'TACACHI','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',151,'TACOPAYA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',152,'TAPACARI','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',153,'TARATA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',154,'TIQUIPAYA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',155,'TIRAQUE','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',156,'TOCO','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',157,'TOLATA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',158,'TOTORA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',159,'VACAS','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',160,'VILA VILA','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',161,'VILLA RIVERO','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',162,'VILLA TUNARI','U');
INSERT INTO ciudad_dep 
VALUES('CB','COCHABAMBA',163,'VINTO','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',1,'SUCRE','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',2,'YOTALA','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',3,'POROMA','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',4,'VILLA AZURDUY','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',5,'TARVITA','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',6,'VILLA ZUDA?EZ','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',7,'PRESTO','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',8,'VILLA MOJOCOYA','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',9,'ICLA','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',10,'PADILLA','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',11,'TOMINA','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',12,'SOPACHUY','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',13,'VILLA ALCALA','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',14,'EL VILLAR','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',15,'MONTEAGUDO','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',16,'HUACARETA','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',17,'TARABUCO','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',18,'YAMPARAEZ','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',19,'CAMARGO','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',20,'SAN LUCAS','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',21,'INCAHUASI','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',22,'VILLA CHARCAS','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',23,'VILLA SERRANO','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',24,'CAMATAQUI (VILLA ABECIA)','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',25,'CULPINA','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',26,'LAS CARRERAS','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',27,'VILLA VACA GUZMAN (MUYUPAMPA)','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',28,'HUACAYA','U');
INSERT INTO ciudad_dep 
VALUES('CH','CHUQUISACA',29,'MACHARETI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',30,'LA PAZ','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',31,'PALCA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',32,'MECAPACA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',33,'ACHOCALLA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',34,'EL ALTO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',35,'ACHACACHI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',36,'ANCORAIMES','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',37,'HUARINA ','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',38,'SANTIAGO DE HUATA ','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',39,'CORO CORO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',40,'CAQUIAVIRI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',41,'CALACOTO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',42,'COMANCHE','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',43,'CHARA?A','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',44,'WALDO BALLIVIAN','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',45,'NAZACARA DE PACAJES','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',46,'SANTIAGO DE CALLAPA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',47,'PUERTO ACOSTA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',48,'MOCOMOCO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',49,'PUERTO CARABUCO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',50,'HUMANATA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',51,'ESCOMA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',52,'CHUMA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',53,'AYATA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',54,'AUCAPATA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',55,'SORATA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',56,'GUANAY','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',57,'TACACOMA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',58,'QUIABAYA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',59,'COMBAYA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',60,'TIPUANI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',61,'MAPIRI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',62,'TEOPONTE','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',63,'APOLO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',64,'PELECHUCO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',65,'VIACHA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',66,'GUAQUI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',67,'TIAHUANACU','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',68,'DESAGUADERO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',69,'SAN ANDRES DE MACHACA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',70,'JESUS DE MACHACA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',71,'TARACO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',72,'LURIBAY','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',73,'SAPAHAQUI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',74,'YACO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',75,'MALLA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',76,'CAIROMA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',77,'INQUISIVI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',78,'QUIME','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',79,'CAJUATA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',80,'COLQUIRI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',81,'ICHOCA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',82,'LICOMA PAMPA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',83,'CHULUMANI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',84,'IRUPANA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',85,'YANACACHI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',86,'PALOS BLANCOS','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',87,'LA ASUNTA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',88,'PUCARANI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',89,'LAJA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',90,'BATALLAS','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',91,'PUERTO PEREZ','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',92,'SICA SICA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',93,'UMALA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',94,'AYO AYO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',95,'CALAMARCA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',96,'PATACAMAYA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',97,'COLQUENCHA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',98,'COLLANA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',99,'COROICO','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',100,'CORIPATA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',101,'IXIAMAS','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',102,'SAN BUENAVENTURA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',103,'GRAL. JUAN JOSE PEREZ (CHARAZANI)','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',104,'CURVA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',105,'COPACABANA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',106,'SAN PEDRO DE TIQUINA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',107,'TITO YUPANQUI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',108,'SAN PEDRO DE CURAHUARA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',109,'PAPEL PAMPA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',110,'CHACARILLA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',111,'SANTIAGO DE MACHACA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',112,'CATACORA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',113,'CARANAVI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',114,'ALTO BENI','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',115,'HUATAJATA','U');
INSERT INTO ciudad_dep 
VALUES('LP','LA PAZ',116,'CHUA COCANI','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',164,'ORURO','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',165,'CARACOLLO','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',166,'EL CHORO','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',167,'SORACACHI (PARIA)','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',168,'CHALLAPATA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',169,'SANTUARIO DE QUILLACAS','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',170,'CORQUE','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',171,'CHOQUECOTA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',172,'CURAHUARA DE CARANGAS','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',173,'TURCO','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',174,'HUACHACALLA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',175,'ESCARA ','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',176,'CRUZ DE MACHACAMARCA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',177,'YUNGUYO DEL LITORAL','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',178,'ESMERALDA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',179,'VILLA POOPO','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',180,'PAZ?A','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',181,'ANTEQUERA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',182,'VILLA HUANUNI','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',183,'MACHACAMARCA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',184,'SALINAS DE GARCI MENDOZA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',185,'PAMPA AULLAGAS','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',186,'SABAYA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',187,'COIPASA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',188,'CHIPAYA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',189,'TOLEDO','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',190,'EUCALIPTUS','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',191,'ANDAMARCA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',192,'BELEN DE ANDAMARCA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',193,'TOTORA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',194,'SANTIAGO DE HUARI','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',195,'LA RIVERA','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',196,'TODOS SANTOS','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',197,'CARANGAS','U');
INSERT INTO ciudad_dep 
VALUES('OR','ORURO',198,'SANTIAGO DE HUAYLLAMARCA','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',325,'COBIJA','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',326,'PORVENIR','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',327,'BOLPEBRA','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',328,'BELLA FLOR','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',329,'PUERTO RICO','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',330,'SAN PEDRO','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',331,'FILADELFIA','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',332,'PUERTO GONZALO MORENO','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',333,'BLANCA FLOR (SAN LORENZO)','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',334,'EL SENA','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',335,'SANTA ROSA DEL ABUNA','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',336,'HUMAITA (INGAVI)','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',337,'NUEVA ESPERANZA','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',338,'VILLA NUEVA (LOMA ALTA)','U');
INSERT INTO ciudad_dep 
VALUES('PA','PANDO',339,'SANTOS MERCADO (RESERVA)','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',199,'POTOSI','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',200,'TINGUIPAYA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',201,'VILLA DE YOCALLA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',202,'BELEN DE URMIRI','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',203,'UNCIA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',204,'CHAYANTA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',205,'LLALLAGUA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',206,'CHUQUIHUTA AYLLU JUCUMANI','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',207,'BETANZOS','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',208,'CHAQUI','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',209,'TACOBAMBA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',210,'COLQUECHACA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',211,'RAVELO','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',212,'POCOATA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',213,'OCURI','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',214,'SAN PEDRO DE BUENA VISTA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',215,'TORO TORO','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',216,'COTAGAITA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',217,'VITICHI','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',218,'SACACA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',219,'CARIPUYO','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',220,'TUPIZA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',221,'ATOCHA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',222,'COLCHA "K"','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',223,'SAN PEDRO DE QUEMES','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',224,'SAN PABLO DE LIPEZ','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',225,'MOJINETE','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',226,'SAN ANTONIO DE ESMORUCO','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',227,'PUNA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',228,'CAIZA "D"','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',229,'CKOCHAS','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',230,'UYUNI','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',231,'TOMAVE','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',232,'PORCO','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',233,'ARAMPAMPA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',234,'ACASIO','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',235,'LLICA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',236,'TAHUA','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',237,'VILLAZON','U');
INSERT INTO ciudad_dep 
VALUES('PT','POTOSI',238,'SAN AGUSTIN','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',250,'SANTA CRUZ DE LA SIERRA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',251,'COTOCA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',252,'PORONGO (AYACUCHO)','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',253,'LA GUARDIA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',254,'EL TORNO','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',255,'WARNES','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',256,'OKINAWA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',257,'SAN IGNACIO','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',258,'SAN MIGUEL','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',259,'SAN RAFAEL','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',260,'BUENA VISTA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',261,'SAN CARLOS','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',262,'YAPACANI','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',263,'SAN JUAN','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',264,'SAN JOSE','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',265,'PAILON','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',266,'ROBORE','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',267,'PORTACHUELO','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',268,'SANTA ROSA DEL SARA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',269,'COLPA BELGICA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',270,'LAGUNILLAS','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',271,'CHARAGUA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',272,'CABEZAS','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',273,'CUEVO','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',274,'GUTIERREZ','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',275,'CAMIRI','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',276,'BOYUIBE','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',277,'VALLEGRANDE','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',278,'EL TRIGAL','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',279,'MORO MORO','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',280,'POSTRERVALLE','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',281,'PUCARA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',282,'SAMAIPATA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',283,'PAMPA GRANDE','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',284,'MAIRANA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',285,'QUIRUSILLAS','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',286,'MONTERO','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',287,'GRAL. SAAVEDRA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',288,'MINEROS','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',289,'FERNANDEZ ALONSO','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',290,'SAN PEDRO','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',291,'CONCEPCION','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',292,'SAN JAVIER','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',293,'SAN RAMON','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',294,'SAN JULIAN','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',295,'SAN ANTONIO DE LOMERIO','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',296,'CUATRO CA?ADAS','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',297,'SAN MATIAS','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',298,'COMARAPA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',299,'SAIPINA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',300,'PUERTO SUAREZ','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',301,'PUERTO QUIJARRO','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',302,'CARMEN RIVERO TORRES','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',303,'ASCENCION DE GUARAYOS','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',304,'URUBICHA','U');
INSERT INTO ciudad_dep 
VALUES('SZ','SANTA CRUZ',305,'EL PUENTE','U');
INSERT INTO ciudad_dep 
VALUES('TJ','TARIJA',239,'TARIJA','U');
INSERT INTO ciudad_dep 
VALUES('TJ','TARIJA',240,'PADCAYA','U');
INSERT INTO ciudad_dep 
VALUES('TJ','TARIJA',241,'BERMEJO','U');
INSERT INTO ciudad_dep 
VALUES('TJ','TARIJA',242,'YACUIBA','U');
INSERT INTO ciudad_dep 
VALUES('TJ','TARIJA',243,'CARAPARI','U');
INSERT INTO ciudad_dep 
VALUES('TJ','TARIJA',244,'VILLAMONTES','U');
INSERT INTO ciudad_dep 
VALUES('TJ','TARIJA',245,'URIONDO (CONCEPCION)','U');
INSERT INTO ciudad_dep 
VALUES('TJ','TARIJA',246,'YUNCHARA','U');
INSERT INTO ciudad_dep 
VALUES('TJ','TARIJA',247,'SAN LORENZO','U');
INSERT INTO ciudad_dep 
VALUES('TJ','TARIJA',248,'EL PUENTE','U');
INSERT INTO ciudad_dep 
VALUES('TJ','TARIJA',249,'ENTRE RIOS','U');
